export const INC_PROGRESS = 'INC_PROGRESS';
export const DEC_PROGRESS = 'DEC_PROGRESS';

export const UPDATE_MANIFEST = 'UPDATE_MANIFEST';
export const RESET_MANIFEST = 'RESET_MANIFEST';
export const RECIEVE_MANIFEST = 'RECIEVE_MANIFEST';
export const SET_PARTIAL_UPDATE = "SET_PARTIAL_UPDATE";
export const CLEAR_PARTIAL_UPDATE = "CLEAR_PARTIAL_UPDATE";

export const RECEIVE_PROFILES = 'RECEIVE_PROFILES';
export const RECEIVE_FLIGHT_OPTIONS = 'RECEIVE_FLIGHT_OPTIONS';
export const RECEIVE_AIRPORTS = "RECEIVE_AIRPORTS";
export const RECEIVE_STATUS_LOGS = "RECEIVE_STATUS_LOGS";

export const RECEIVE_MANIFEST_LOGS = 'RECEIVE_MANIFEST_LOGS';

export const RECIEVE_FIRE_CHECK = "RECIEVE_FIRE_CHECK";
export const UPDATE_FIRE_CHECK = "UPDATE_FIRE_CHECK";
export const FIRE_CHECK_PROGRESS = "FIRE_CHECK_PROGRESS";
export const FIRE_CHECK_ERRORS = "FIRE_CHECK_ERRORS";

export const VALIDATE_COMPLETE = "VALIDATE_COMPLETE";
export const SET_VALIDATE_STATUS = "SET_VALIDATE_STATUS";

export const UPDATE_FLITHGT_FILTER = "UPDATE_FLITHGT_FILTER";
export const RECEIVE_FLIGHTS = "RECEIVE_FLIGHTS";
export const RESET_PICK_FLIGHT = "RESET_PICK_FLIGHT";
export const FLIGHTS_LOADING  = "FLIGHTS_LOADING";
export const SET_FLIGHT_ID = "SET_FLIGHT_ID";

export const RESET_EDIT_FLIGHT = "RESET_EDIT_FLIGHT";
export const SET_EDIT_FLIGHT = "SET_EDIT_FLIGHT";
export const UPDATE_EDIT_FLIGHT = "UPDATE_EDIT_FLIGHT";

export const SET_PENDING = 'CONFIRMATION/SET_PENDING';
export const SET_CONFIRMATION = 'CONFIRMATION/SET_CONFIRMATION';
export const RESET_CONFIRMATION = 'CONFIRMATION/RESET_CONFIRMATION';
export const UPDATE_APPROVAL_DATA = 'CONFIRMATION/UPDATE_APPROVAL_DATA';

export const EDIT_FLIGHT_SET_PROGRESSS = 'EDIT_FLIGHT_SET_PROGRESSS';

export const DUTY_UPDATING = 'DUTY_UPDATING'
export const UPDATE_DUTY = 'UPDATE_DUTY'

export const SET_NUMBER_CHANGE_MODAL = 'SET_NUMBER_CHANGE_MODAL';

export const SAVED_INDICATION_ON = 'SAVED_INDICATION_ON';
export const SAVED_INDICATION_OFF = 'SAVED_INDICATION_OFF';
