export const SET_DATETIME_OUT_1 = "SET_DATETIME_OUT_1";
export const SET_DATETIME_OUT_2 = "SET_DATETIME_OUT_2";
export const SET_AIRCRAFT_FILTER = "SET_AIRCRAFT_FILTER";
export const SET_IS_LAST_FILTER = "SET_IS_LAST_FILTER";
export const SET_DISTINCT = "SET_DISTINCT";
export const SET_FEATURE_FLIGHTLOG = "SET_FEATURE_FLIGHTLOG";
export const SET_FLIGHTLOGS = "SET_FLIGHTLOGS";
export const SET_TOTAL = "SET_TOTAL";
export const RESET_PAGE = "RESET_PAGE";
export const RESET_FILTERS = "RESET_FILTERS";
export const SET_SIZE = "SET_SIZE";
export const SET_PROGRESS = "SET_PROGRESS";
export const SET_SELECTED_ID = "SET_SELECTED_ID";

// Logs
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SET_PAGE = "SET_PAGE";
export const SET_LOAD_STATUS = 'SET_LOAD_STATUS';
export const DEFAULT_PAGE_SIZE = 100;
export const RESET = 'RESET';
export const SET_LOGS = 'SET_LOGS';
export const SET_MANIFEST_LOGS = 'SET_MANIFEST_LOGS';

export const STATUS_OPEN = 1;
export const STATUS_PENDING_PIC = 2;
export const STATUS_DISPATCH_PENDING = 3;
export const STATUS_DISPATCH_RE_OPEN = 4;
export const STATUS_COMPLETED = 5;

export const NO_DIVERSION = 0;
export const DIVERSION = 1;
export const AIR_RETURN = 2;
export const GATE_RETURN = 3;

export const SET_FLIGHTLOG = 'SET_FLIGHTLOG';
export const SET_DIVERSION_TYPE = 'SET_DIVERSION_TYPE';
export const SET_ACTUAL_DESTINATION = 'SET_ACTUAL_DESTINATION';
export const SET_ACTUAL_ORIGIN = 'SET_ACTUAL_ORIGIN';

export const SET_PARTIAL_UPDATE = 'SET_PARTIAL_UPDATE';
export const CLEAR_PARTIAL_UPDATE = 'CLEAR_PARTIAL_UPDATE';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const SET_NIGHT_INFO_PROGRESS = 'SET_NIGHT_INFO_PROGRESS';

export const SET_DELETE_LOG = 'SET_DELETE_LOG';
export const RESET_DELETE_LOG = 'RESET_DELETE_LOG';
export const DELETING_LOG = 'DELETING_LOG';

export const INC_CALC_NIGHT_TIME_FLAG = 'INC_CALC_NIGHT_TIME_FLAG';

export const SET_COMPLETE_LOG = 'SET_COMPLETE_LOG';
export const RESET_COMPLETE_LOG = 'RESET_COMPLETE_LOG';
export const COMPLETING_LOG = 'COMPLETING_LOG';

export const SAVED_INDICATION_ON = 'SAVED_INDICATION_ON';
export const SAVED_INDICATION_OFF = 'SAVED_INDICATION_OFF';
