export const LUXON_US_DATE_FORMAT = 'MM/dd/yyyy';
export const FNS_US_DATE_FORMAT = 'MM/dd/yyyy';
export const PIC_RANK_ID = 1;
export const SIC_RANK_ID = 2;
export const PILOT_RANKS = {
  [PIC_RANK_ID]: 'PIC',
  [SIC_RANK_ID]: 'SIC',
};

export const TYPE_OFF = 'off';
export const TYPE_PAIR = 'pair';
export const TYPE_SHIFT = 'shift';
export const RESERVE_TYPE_ID = 0;
export const OFFICE_TYPE_ID = 1;
export const TRAINING_TYPE_ID = 2;
export const TRAVEL_TYPE_ID = 3;
export const TABS = [
  'Scheduled',
  'Reserve',
  'Training',
  'Office',
  'Off',
  'Holidays',
  'Travel',
];
export const TAB_ID_RESERVE_ID_MAP = {
  1: RESERVE_TYPE_ID,
  2: TRAINING_TYPE_ID,
  3: OFFICE_TYPE_ID,
  4: TRAVEL_TYPE_ID,
};
export const OFF_OFF_TYPE_ID = 1;
export const N_A_OFF_TYPE_ID = 2;
export const ON_DAY_LINK = 'ON_DAY_LINK';
export const NEXT_DAY_LINK = 'NEXT_DAY_LINK';

export const SICK_TYPE = 1;
export const HALF_SICK_TYPE = 2;

export const INC_PROGRESS = 'INC_PROGRESS';
export const DEC_PROGRESS = 'DEC_PROGRESS';

/**
 * calendar related
 */
export const CHANGE_RANK = 'CHANGE_RANK';
export const CHANGE_BASE_AIRPORTS = 'CHANGE_BASE_AIRPORTS';
export const CHANGE_AIRCRAFT_TYPE = 'CHANGE_AIRCRAFT_TYPE';
export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_ACTUAL = 'CHANGE_ACTUAL';
export const CHANGE_NEW_HIRES = 'CHANGE_NEW_HIRES';
export const CHANGE_PILOT_NAME = 'CHANGE_PILOT_NAME';
export const SET_PILOT_GRID = 'SET_PILOT_GRID';
export const SET_PILOT_PAYROLL = 'SET_PILOT_PAYROLL';
export const SET_PAYROLL_MODE = 'SET_PAYROLL_MODE';
export const SET_ACTIVE_PILOT = 'SET_ACTIVE_PILOT';
export const SET_ACTIVE_DATE = 'SET_ACTIVE_DATE';
export const SET_ACTIVE_DATE_RANGE = 'SET_ACTIVE_DATE_RANGE';
export const SET_HOVERED_DATE = 'SET_HOVERED_DATE';
export const SET_HIGHLIGHTED_PILOT = 'SET_HIGHLIGHTED_PILOT';
export const SET_ACTIVE_COORDINATES = 'SET_ACTIVE_COORDINATES';

export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_DAY_SORT = 'CHANGE_DAY_SORT';
export const FIRST_NAME = 'pilot.first_name';
export const LAST_NAME = 'pilot.last_name';
export const BASE = 'pilot.base';
export const RANK = 'pilot.rank';
export const SENIORITY = 'pilot.seniority_number';
export const EMPLOYEE = 'pilot.employee_number';


export const UPDATE_RECORDS = 'UPDATE_RECORDS';
export const ADD_PENDING_PILOTS = 'ADD_PENDING_PILOTS';
export const REMOVE_PENDING_PILOTS = 'REMOVE_PENDING_PILOTS';
export const UPDATE_PILOT_TOTALS = 'UPDATE_PILOT_TOTALS';

export const OPTIMISTIC_ADD_RECORD = 'OPTIMISTIC_ADD_RECORD';
export const OPTIMISTIC_SET_OFF_RECORD = 'OPTIMISTIC_SET_OFF_RECORD';
export const OPTIMISTIC_REMOVE_RECORD = 'OPTIMISTIC_REMOVE_RECORD';
export const SET_SHOW_ASSIGNED_FLIGHTS_DATE = 'SET_SHOW_ASSIGNED_FLIGHTS_DATE';
export const SET_SHOW_FDT_CALENDAR_PILOT = 'SET_SHOW_FDT_CALENDAR_PILOT';
export const SET_SHOW_MANIFEST_ID = 'SET_SHOW_MANIFEST_ID';
export const SET_ACTIVE_RECORDS = 'SET_ACTIVE_RECORDS';
export const SET_LINKED_PAIRS = 'SET_LINKED_PAIRS';
export const CHANGE_LINKAGE_STATE = 'CHANGE_LINKAGE_STATE';

/**
 * shift templates related
 */
export const CHANGE_EDITABLE_PAIRING_TEMPLATE_GROUP = 'CHANGE_EDITABLE_PAIRING_TEMPLATE_GROUP';
export const CHANGE_EDITABLE_PAIRING_TEMPLATE_GROUP_TEMPLATES = 'CHANGE_EDITABLE_PAIRING_TEMPLATE_GROUP_TEMPLATES';
export const CHANGE_EDITABLE_PAIRING_TEMPLATE = 'CHANGE_EDITABLE_PAIRING_TEMPLATE';
export const UPDATE_SHELL = 'UPDATE_SHELL';
export const UPDATE_PAIRING_TEMPLATE = 'UPDATE_PAIRING_TEMPLATE';
export const ADD_FLIGHT_TO_PAIRING_TEMPLATE = 'ADD_FLIGHT_TO_PAIRING_TEMPLATE';
export const ADD_NEXT_DAY_FLIGHT_TO_PAIRING_TEMPLATE = 'ADD_NEXT_DAY_FLIGHT_TO_PAIRING_TEMPLATE';
export const REMOVE_FLIGHT_FROM_PAIRING_TEMPLATE = 'REMOVE_FLIGHT_FROM_PAIRING_TEMPLATE';
export const SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX';
export const SET_AFFECT = 'SET_AFFECT';
export const HIDE_AFFECT = 'HIDE_AFFECT';
export const SHOW_AFFECT = 'SHOW_AFFECT';
export const SET_DAY_OFF_TYPES = 'SET_DAY_OFF_TYPES';
export const ADD_DAY_OFF_TYPE = 'ADD_DAY_OFF_TYPE';
export const DELETE_DAY_OFF_TYPE = 'DELETE_DAY_OFF_TYPE';
export const PATCH_DAY_OFF_TYPE = 'PATCH_DAY_OFF_TYPE';
export const SET_EDITABLE_RESERVE_TEMPLATE = 'SET_EDITABLE_RESERVE_TEMPLATE';
export const SET_SHIFT_TEMPLATE_CHANGES = 'SET_SHIFT_TEMPLATE_CHANGES';
export const UPDATE_RESERVE_TEMPLATE = 'UPDATE_RESERVE_TEMPLATE';
export const UPDATE_NOT_SUBMITTED_DAY_OFF_FORM = 'UPDATE_NOT_SUBMITTED_DAY_OFF_FORM';
export const ADD_FILTER_BY_FLIGHT_ID = 'ADD_FILTER_BY_FLIGHT_ID';
export const REMOVE_FILTER_BY_FLIGHT_ID = 'REMOVE_FILTER_BY_FLIGHT_ID';
export const SET_COLLISIONS = 'SET_COLLISIONS';
export const SET_AFFECT_LOADING = 'SET_AFFECT_LOADING';
export const SET_AFFECT_TEMPLATE_ID = 'SET_AFFECT_TEMPLATE_ID';
export const SET_CHANGES_LOADING = 'SET_CHANGES_LOADING';

export const SET_EDITABLE_GROUP_FORM = 'SET_EDITABLE_GROUP_FORM';
export const SET_PLAIN_GROUP_LIST = 'SET_PLAIN_GROUP_LIST';


/**
 * shifts related
 */
export const CHANGE_EDITABLE_PAIRING = 'CHANGE_EDITABLE_PAIRING';
export const ADD_FLIGHT_TO_PAIRING = 'ADD_FLIGHT_TO_PAIRING';
export const REMOVE_FLIGHT_FROM_PAIRING = 'REMOVE_FLIGHT_FROM_PAIRING';
export const UPDATE_PAIRING = 'UPDATE_PAIRING';
export const REMOVE_PAIRING = 'REMOVE_PAIRING';
export const TOGGLE_PAIRING_ADDITION_MODAL = 'TOGGLE_PAIRING_ADDITION_MODAL';
export const SET_EDITABLE_RESERVE_SHIFT = 'SET_EDITABLE_RESERVE_SHIFT';
export const UPDATE_RESERVE_SHIFT = 'UPDATE_RESERVE_SHIFT';
export const SET_CONFLICT_CONTAINED_SHIFT_ID = 'SET_CONFLICT_CONTAINED_SHIFT_ID';
export const SET_CONFLICT_FLIGHT = 'SET_CONFLICT_FLIGHT';
export const SET_LAST_EDITED_SHIFT_ID = 'SET_LAST_EDITED_SHIFT_ID';
export const ADD_FLIGHT_SHIFT = 'ADD_FLIGHT_SHIFT';
export const REMOVE_FLIGHT_SHIFT = 'REMOVE_FLIGHT_SHIFT';
export const ADD_NON_LISTED_SHIFT = 'ADD_NON_LISTED_SHIFT';
export const GO_TO_PREVIOUS_EDITABLE = 'GO_TO_PREVIOUS_EDITABLE';
export const TOGGLE_AFFECT_MODAL = 'TOGGLE_AFFECT_MODAL';
export const UPDATE_PAIR_FORM = 'UPDATE_PAIR_FORM';
export const RESET_PAIR_FORM = 'RESET_PAIR_FORM';
export const ADD_PAIRING_SPLIT = 'ADD_PAIRING_SPLIT';
export const REMOVE_PAIRING_SPLIT = 'REMOVE_PAIRING_SPLIT';
export const CLEAR_PAIRING_SPLIT = 'CLEAR_PAIRING_SPLIT';

/**
 * revisions
 */
export const SET_REVISIONS = 'SET_REVISIONS';
export const ADD_REVISION = 'ADD_REVISION';
export const REMOVE_REVISION = 'REMOVE_REVISION';
export const SET_ACTIVE_REVISION = 'SET_ACTIVE_REVISION';
export const PUBLISH_REVISION = 'PUBLISH_REVISION';
export const SET_DRAFT_REVISION = 'SET_DRAFT_REVISION';
export const SET_DRAFT_ADDITION_POPUP_SHOWN = 'SET_DRAFT_ADDITION_POPUP_SHOWN';
export const SET_NEWLY_CREATED_FIRST_DRAFT = 'SET_NEWLY_CREATED_FIRST_DRAFT';
export const SET_REVISION_HAS_CHANGES = 'SET_REVISION_HAS_CHANGES';

/**
 * assigned flights
 */
export const SET_ASSIGNED_FLIGHTS = 'SET_ASSIGNED_FLIGHTS';
export const SET_ASSIGNED_PAIRS = 'SET_ASSIGNED_PAIRS';
export const SET_ASSIGNED_FLIGHT_STATUS = 'SET_ASSIGNED_FLIGHT_STATUS';
export const SET_TIMEZONE = 'SET_TIMEZONE';

/**
 * Gantt
 */
export const CHANGE_RANGE = 'CHANGE_RANGE';
export const SET_GANTT_PILOT_LIST = 'SET_GANTT_PILOT_LIST';

/**
 * Pilot view
 */
export const SET_PILOT_VIEW = 'SET_PILOT_VIEW';
